#!/bin/bash
set -x
APP=go-omdb
APP_PATH=.
mkdir $APP_PATH/tmp
#cp pom.xml $APP_PATH/tmp
#cp -rf src     $APP_PATH/tmp
docker build -f $APP_PATH/Dockerfile -t $APP  $APP_PATH
rm -rf $APP_PATH/tmp

docker rm -f $APP
docker run --name $APP -p ${PORT}:8080 -dt $APP

docker exec $APP ./main "Long Shot"


